// GENERATED by tools/evidence/se_hover_wind_cadence_table.py -- do not edit.
// Source: knowledge_base/mmx1/bosses/storm-eagle/hover_wind_cadence.json
//
// Plan task R5.2. The hover wind is not continuous: the boss slot's +0x03 gate
// byte blows (0x04) for a multiple of 120 frames and then pauses (0x02/0x06)
// for exactly 40, and every observation run that reaches a Hover step
// reproduces the same sequence frame for frame -- so this is a SCHEDULE keyed
// to the step's own frame counter, not a distribution.
//
// NONCLAIM: a Hover step whose whole observed window is one blow (the corpus
// lost it to the player's death before any pause) is NOT in kCovered, and the
// wind blows for its whole length as it did before this table.

#pragma once

namespace mmx::boss_se_hover_wind {

struct Interval {
    int loopStepIndex;
    int firstFrame;   // inclusive, offset from the step's first frame
    int lastFrame;    // inclusive
};

inline constexpr Interval kBlowIntervals[] = {
    {0, 1, 240},
    {2, 87, 446},
    {2, 488, 607},
    {4, 92, 331},
    {7, 1, 173},
};
inline constexpr int kIntervalCount =
    sizeof(kBlowIntervals) / sizeof(kBlowIntervals[0]);

// The loop steps whose cadence the corpus actually measured end to end.
inline constexpr int kCovered[] = {0, 2, 4};
inline constexpr int kCoveredCount = sizeof(kCovered) / sizeof(kCovered[0]);

inline bool covered(int loopStepIndex) {
    for (int i = 0; i < kCoveredCount; ++i) {
        if (kCovered[i] == loopStepIndex) return true;
    }
    return false;
}

// stepFrame is 0-based within the Hover step.
inline bool blowing(int loopStepIndex, int stepFrame) {
    if (!covered(loopStepIndex)) return true;
    for (int i = 0; i < kIntervalCount; ++i) {
        const Interval& v = kBlowIntervals[i];
        if (v.loopStepIndex == loopStepIndex && stepFrame >= v.firstFrame &&
            stepFrame <= v.lastFrame) {
            return true;
        }
    }
    return false;
}

} // namespace mmx::boss_se_hover_wind
