// boss_se_intro_timeline.h - Storm Eagle's measured boss-room intro.
// GENERATED by tools/evidence/se_intro_timeline_table.py from
// knowledge_base/mmx1/bosses/storm-eagle/intro_timeline.json. Do not edit by
// hand; tools/tests/test_se_intro_timeline_pin.py re-derives and compares.
//
// Ticks are relative to the frame the boss slot goes live (source frame
// 14858); the engine's activation frame is tick 0. Pre-intro
// ticks 0..62 are hidden. The entrance flight runs ticks
// 64..213: y 47 -> 196, one px per tick, at x 6192
// (the corpus x takes the values {6190, 6192}; the 2 px wobble is not modelled).
// The HP gauge fills with 31 $0C mailbox ticks every 2 ticks from tick
// 262 (display HP 1..31) and reads 32 from tick 324. Fight on
// at tick 360. Gauge visibility before the fill is a KB nonclaim: the
// engine shows the empty gauge from activation (display HP 0, as the corpus
// records from the slot-live frame).
#pragma once

namespace mmx::boss_se_intro_timeline {

inline constexpr int kSlotLiveFrame = 14858;
inline constexpr int kIntroStartTick = 63;
inline constexpr int kFlightFirstTick = 64;
inline constexpr int kFlightLastTick = 213;
inline constexpr int kFlightStartY = 47;
inline constexpr int kFlightEndY = 196;
inline constexpr int kFlightX = 6192;
inline constexpr int kHpFillFirstTick = 262;
inline constexpr int kHpFillLastTick = 322;
inline constexpr int kHpFillSpacing = 2;
inline constexpr int kHpFillTicks = 31;
inline constexpr int kHpFullTick = 324;
inline constexpr int kMaxDisplayHealth = 32;
inline constexpr int kFightTick = 360;
inline constexpr int kFillApuCommand = 0x0C;

struct Frame {
    float x = 0.0f;
    float y = 0.0f;
    int displayHealth = 0;
    bool visible = false;
    bool emitFillApu = false;
    bool fightOn = false;
};

constexpr Frame frameAt(int tick) {
    Frame f;
    f.x = static_cast<float>(kFlightX);
    if (tick < kFlightFirstTick) {
        f.y = static_cast<float>(kFlightStartY);
    } else if (tick <= kFlightLastTick) {
        f.y = static_cast<float>(kFlightStartY + (tick - kFlightFirstTick));
    } else {
        f.y = static_cast<float>(kFlightEndY);
    }
    f.visible = tick >= kFlightFirstTick;
    if (tick >= kHpFullTick) {
        f.displayHealth = kMaxDisplayHealth;
    } else if (tick >= kHpFillFirstTick) {
        f.displayHealth = 1 + (tick - kHpFillFirstTick) / kHpFillSpacing;
    }
    f.emitFillApu = tick >= kHpFillFirstTick && tick <= kHpFillLastTick &&
                    (tick - kHpFillFirstTick) % kHpFillSpacing == 0;
    f.fightOn = tick == kFightTick;
    return f;
}

}  // namespace mmx::boss_se_intro_timeline
