// boss_se_fight_loop.h - Storm Eagle's measured fight-loop order.
// GENERATED by tools/evidence/se_b5_e6_fight_loop_table.py from
// knowledge_base/mmx1/bosses/storm-eagle/fight_timeline.json. Do not edit by
// hand; tools/tests/test_se_fight_loop_pin.py re-derives and compares.
//
// $source: the se_movie_dense corpus of David's 2026-07-26 movie, fight window
// 15218..18982. SE-B2 decoded the live fight as a FIXED
// loop in which only durations modulate: Hover is the hub, Chain is the
// climb/swoop/descent chain, Gust is the wind state, Recover is the
// post-chain screech.
//
// LAW: the ORDER below. NONCLAIM: the per-step FRAME COUNTS are ONE
// observation, not a law - kObservedFrames exists so the engine has a
// concrete duration and so a second fight can refute it. In particular the
// Chain steps ran 1 swoop then 9 swoops; that count is observed, not pinned.
// Gust's 200 is the one duration SE-B2 saw hold across corpora.
//
// kLoopRestartIndex: the movie window holds ONE pass, so this table alone
// cannot say where a second cycle re-enters. SE-B2's observation corpus can -
// its sequenceLaw records the climb opening cycle 2 - so step 0, the one-time
// fight-on entry hold, is left behind on every subsequent cycle.

#pragma once

namespace mmx::boss_se_fight_loop {

enum class SeLoopState { Hover, Chain, Gust, Recover };

struct Step {
    SeLoopState state;
    int observedFrames;
};

inline constexpr Step kLoop[] = {
    {SeLoopState::Hover, 281},     // 15218..15498
    {SeLoopState::Chain, 388},     // 15499..15886
    {SeLoopState::Hover, 651},     // 15887..16537
    {SeLoopState::Gust, 200},     // 16538..16737
    {SeLoopState::Hover, 372},     // 16738..17109
    {SeLoopState::Chain, 1382},    // 17110..18491
    {SeLoopState::Recover, 276},     // 18492..18767
    {SeLoopState::Hover, 214},     // 18768..18981
};
inline constexpr int kStepCount = 8;
inline constexpr int kFightOnFrame = 15218;
inline constexpr int kLoopRestartIndex = 1;

} // namespace mmx::boss_se_fight_loop
