// boss_se_recover_motion.h - Storm Eagle's measured s4 Recover motion.
// GENERATED by tools/evidence/se_b5_e7_recover_motion_table.py from
// knowledge_base/mmx1/bosses/storm-eagle/recover_kinematics.json. Do not edit
// by hand; tools/tests/test_se_recover_motion_pin.py re-derives and compares.
//
// SCOPE: step 6 of boss_se_fight_loop::kLoop, source frames 18492..18767.
// With boss_se_hold_motion.h (5 steps) and boss_se_chain_motion.h (2), this
// completes all eight.
//
// UNITS: dy is in 1/256 px per frame, the same fixed point the hold table
// uses. x is fixed ("xFixed" in the KB), so only y moves. Screen y grows
// downward: the pattern is a DESCENT of 85 px back to the hover row.
//
// NONCLAIM: one observed fight. The dy values are exact within it -- the
// pattern is verified at generation time to sum to the recorded net travel --
// and the 189 flat frames at the end are that pass's tail.

#pragma once

#include <array>

namespace mmx::boss_se_recover_motion {

struct DyRun {
    int dyFp;    // 1/256 px per frame
    int frames;
};

inline constexpr int kStepIndex = 6;
inline constexpr int kRunCount = 3;
inline constexpr std::array<DyRun, kRunCount> kRuns{{{0, 1}, {256, 85}, {0, 189}}};
inline constexpr int kNetFp = 21760;   // +85 px over the step

// Vertical delta for the Recover step at a given frame offset, in 1/256 px.
// Returns 0 for any other step, so a caller can add it unconditionally.
constexpr int dyFpAt(int stepIndex, int frameInStep) {
    if (stepIndex != kStepIndex) return 0;
    int cursor = 0;
    for (const auto& run : kRuns) {
        cursor += run.frames;
        if (frameInStep < cursor) return run.dyFp;
    }
    return 0;
}

constexpr bool hasMeasuredMotion(int stepIndex) { return stepIndex == kStepIndex; }

} // namespace mmx::boss_se_recover_motion
