// boss_se_hold_motion.h - Storm Eagle's measured hold-state motion.
// GENERATED by tools/evidence/se_b5_e7_hold_motion_table.py from
// knowledge_base/mmx1/bosses/storm-eagle/attack_kinematics.json. Do not edit
// by hand; tools/tests/test_se_hold_motion_pin.py re-derives and compares.
//
// SCOPE: 5 of the 8 fight-loop steps. Every Hover hold and the Gust
// carry an exact per-frame vertical law; the two Chain steps and the s4
// Recover do NOT and are deliberately absent - the Chain's climb/swoop/descent
// instance lengths do not close against the step duration without assuming the
// hit-pause structure, and s4 is an open question in the KB.
//
// UNITS: dy is in 1/256 px per frame, the same fixed-point the CP slide law
// uses. x is fixed in every hold ("xFixed"), so only y moves.
//
// The runs are RELATIVE deltas. This table deliberately does not carry the
// absolute source y (196.0 px at the hover row): binding that needs the boss
// anchor bridge, which is E4/E5, not this slice.
//
// NONCLAIM: as with the loop order, these are ONE observed fight. The dy
// values are exact within it - each pattern is verified at generation time to
// sum to the recorded net travel - but the KB records duration RANGES for
// several of these holds across corpora.

#pragma once

#include <array>

namespace mmx::boss_se_hold_motion {

struct DyRun {
    int dyFp;    // 1/256 px per frame
    int frames;
};

inline constexpr int kMaxRuns = 3;

struct HoldMotion {
    int stepIndex;   // index into boss_se_fight_loop::kLoop
    int runCount;
    DyRun runs[kMaxRuns];
};

inline constexpr std::array<HoldMotion, 5> kHoldMotions{{
    {0, 1, {{0, 280}, {0, 0}, {0, 0}}},  // source f15218
    {2, 3, {{0, 1}, {256, 85}, {0, 564}}},  // source f15887
    {3, 3, {{0, 1}, {-256, 90}, {0, 108}}},  // source f16538
    {4, 3, {{0, 1}, {256, 90}, {0, 280}}},  // source f16738
    {7, 1, {{0, 214}, {0, 0}, {0, 0}}},  // source f18768
}};

// Vertical delta for a step at a given frame offset, in 1/256 px.
// Returns 0 for steps with no measured motion law (the Chain and Recover
// steps), which is a deliberate hold, not an omission.
constexpr int dyFpAt(int stepIndex, int frameInStep) {
    for (const auto& motion : kHoldMotions) {
        if (motion.stepIndex != stepIndex) continue;
        int cursor = 0;
        for (int i = 0; i < motion.runCount; ++i) {
            cursor += motion.runs[i].frames;
            if (frameInStep < cursor) return motion.runs[i].dyFp;
        }
        return 0;  // past the recorded pattern: hold
    }
    return 0;
}

constexpr bool hasMeasuredMotion(int stepIndex) {
    for (const auto& motion : kHoldMotions) {
        if (motion.stepIndex == stepIndex) return true;
    }
    return false;
}

}  // namespace mmx::boss_se_hold_motion
