// boss_se_chain_motion.h - Storm Eagle's measured Chain-step motion.
// GENERATED by tools/evidence/se_b5_e7_chain_motion_table.py from
// knowledge_base/mmx1/bosses/storm-eagle/attack_kinematics.json and
// fight_timeline.json. Do not edit by hand;
// tools/tests/test_se_chain_motion_pin.py re-derives and compares.
//
// SCOPE: the two Chain steps of boss_se_fight_loop::kLoop (indices 1 and 5):
// climb, top-teleport, swoop(s) with the 2-frame blips between chained
// swoops, top-teleport, descent. The Recover step stays a hold (open KB
// question). The swoop count (1 then 9) is observed, not pinned.
//
// UNITS: 1/256 px. MOVE segments are per-frame deltas, applied at tick t
// for frame t (the boss_se_hold_motion.h convention); SET segments are
// absolute source positions (the top-teleports) and occupy one frame each,
// the last delta of the flat run before the move. The shipped spawn
// (6192,196) is the source hover position (1585152, 50176) / 256, so both
// kinds share one frame.
//
// hitPauseFrames: frames the corpus spent in X-shot hit pauses inside the
// last swoop of step 5. They belong to X's hits, not to the boss law, so
// the table replays the law and the step holds them at its end.

#pragma once

#include <array>

namespace mmx::boss_se_chain_motion {

enum SegKind : int { kMove = 0, kSet = 1 };

struct Seg {
    int kind;    // kMove: a = dxFp, b = dyFp per frame; kSet: a = xFp, b = yFp
    int a;
    int b;
    int frames;  // kSet: always 1, the teleport frame
};

inline constexpr int kMaxSegs = 40;

struct ChainMotion {
    int stepIndex;      // index into boss_se_fight_loop::kLoop
    int segCount;
    int hitPauseFrames; // held at the end of the step
    Seg segs[kMaxSegs];
};

inline constexpr std::array<ChainMotion, 2> kChainMotions{{
    {1, 8, 0, {{0, 0, 0, 1}, {0, 0, -384, 130}, {1, 1628928, -128, 1}, {0, -1024, 1024, 80}, {0, 0, 0, 39}, {1, 1547008, -128, 1}, {0, 0, 256, 112}, {0, 0, 0, 24}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}, {0, 0, 0, 0}}},  // source f15499..f15886, 388 frames
    {5, 40, 8, {{0, 0, 0, 1}, {0, 0, -384, 131}, {1, 1579264, -384, 1}, {0, -1024, 1024, 81}, {0, 0, 0, 40}, {0, 0, 0, 1}, {1, 1476864, -512, 1}, {0, 1024, 1024, 81}, {0, 0, 0, 40}, {0, 0, 0, 1}, {1, 1599744, -640, 1}, {0, -1024, 1024, 81}, {0, 0, 0, 40}, {0, 0, 0, 1}, {1, 1590272, -512, 1}, {0, -1024, 1024, 81}, {0, 0, 0, 40}, {0, 0, 0, 1}, {1, 1591808, -640, 1}, {0, -1024, 1024, 81}, {0, 0, 0, 40}, {0, 0, 0, 1}, {1, 1597440, -512, 1}, {0, -1024, 1024, 81}, {0, 0, 0, 40}, {0, 0, 0, 1}, {1, 1599488, -640, 1}, {0, -1024, 1024, 81}, {0, 0, 0, 40}, {0, 0, 0, 1}, {1, 1594112, -512, 1}, {0, -1024, 1024, 81}, {0, 0, 0, 40}, {0, 0, 0, 1}, {1, 1495040, -640, 1}, {0, 1024, 1024, 81}, {0, 0, 0, 39}, {1, 1577984, -128, 1}, {0, 0, 256, 112}, {0, 0, 0, 24}}},  // source f17110..f18491, 1382 frames
}};

struct Delta {
    bool set;  // true: (a, b) is an absolute position
    int a;
    int b;
};

// Motion for a Chain step at a frame offset: the delta to add this frame,
// or (set) the absolute position to take. Past the recorded program the
// step holds.
constexpr Delta at(int stepIndex, int frameInStep) {
    for (const auto& motion : kChainMotions) {
        if (motion.stepIndex != stepIndex) continue;
        int cursor = 0;
        for (int i = 0; i < motion.segCount; ++i) {
            const Seg& seg = motion.segs[i];
            cursor += seg.frames;
            if (frameInStep < cursor) return {seg.kind == kSet, seg.a, seg.b};
        }
        return {false, 0, 0};
    }
    return {false, 0, 0};
}

constexpr bool hasMeasuredMotion(int stepIndex) {
    for (const auto& motion : kChainMotions) {
        if (motion.stepIndex == stepIndex) return true;
    }
    return false;
}

}  // namespace mmx::boss_se_chain_motion
