// enemy_bat_drift_law.h — GENERATED by tools/evidence/bat_drift_law_table.py.
// Do not edit by hand; edit the measurement and regenerate.
//
// Source: knowledge_base/mmx1/enemies/oid_0x2D_bat_family_pending/
//         direction_law.json (plan task R1.0x2D step 2b, 2026-09-06),
//         reduced from 7 instances of OID 0x2D in David's Chill Penguin
//         movie: 41 direction runs, 34 completed holds.
//
// The bat hangs motionless at its spawn for a drawn number of frames,
// then flies at exactly one pixel per frame in a drawn direction, held
// for a drawn number of frames, and repeats. No dependence on the PRNG
// state, on the previous direction or on X's side was established at
// these counts (direction_law.json records all three negative tests), so
// the three draws are independent.
//
// Velocities are the source's raw slot fields at 1/256 px per frame, and
// vy > 0 moves UP: the source integrates xf += vx and yf -= vy exactly.
#pragma once

#include <cstdint>

namespace mmx::enemy_bat_drift_law {

struct WeightedValue {
    int value;
    int count;
};

struct WeightedDirection {
    int vx;      // 1/256 px per frame
    int vy;      // 1/256 px per frame, positive is UP
    int count;
};

inline constexpr int kFixedPointDivisor = 256;

// Frames held motionless at the spawn. The velocity field is non-zero
// during it, so this is a state and not a zero speed.
inline constexpr WeightedValue kHangFrames[] = {
    {30, 3},
    {31, 1},
    {32, 1},
    {35, 2},
};
inline constexpr int kHangFramesCount = 4;
inline constexpr int kHangFramesWeight = 7;

// Frames one direction is held before the next draw.
inline constexpr WeightedValue kHoldFrames[] = {
    {20, 12},
    {21, 4},
    {22, 5},
    {23, 11},
    {40, 2},
};
inline constexpr int kHoldFramesCount = 5;
inline constexpr int kHoldFramesWeight = 34;

// Every direction observed, ordered by screen angle atan2(-vy, vx).
inline constexpr WeightedDirection kDirections[] = {
    {-229, 114, 1},  // -153.54 deg
    {153, 204, 1},  // -53.13 deg
    {204, 153, 2},  // -36.87 deg
    {228, 114, 2},  // -26.57 deg
    {248, 62, 6},  // -14.04 deg
    {256, 0, 4},  // 0.00 deg
    {248, -62, 5},  // 14.04 deg
    {228, -114, 3},  // 26.57 deg
    {204, -154, 3},  // 37.05 deg
    {180, -181, 1},  // 45.16 deg
    {114, -229, 2},  // 63.54 deg
    {62, -248, 1},  // 75.96 deg
    {0, -256, 2},  // 90.00 deg
    {-114, -229, 3},  // 116.46 deg
    {-154, -205, 4},  // 126.91 deg
    {-205, -154, 1},  // 143.09 deg
};
inline constexpr int kDirectionsCount = 16;
inline constexpr int kDirectionsWeight = 41;

// Draw one entry from a weighted table with a value in [0, weight).
inline int pickWeightedValue(const WeightedValue* table, int count,
                             int weight, int roll) {
    if (count <= 0 || weight <= 0) return 0;
    int remaining = roll % weight;
    for (int i = 0; i < count; ++i) {
        remaining -= table[i].count;
        if (remaining < 0) return table[i].value;
    }
    return table[count - 1].value;
}

inline int pickDirectionIndex(int roll) {
    int remaining = roll % kDirectionsWeight;
    for (int i = 0; i < kDirectionsCount; ++i) {
        remaining -= kDirections[i].count;
        if (remaining < 0) return i;
    }
    return kDirectionsCount - 1;
}

} // namespace mmx::enemy_bat_drift_law
